<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAPW10000000164" name="Blue coat cloud Service Tests " tests="4" failures="4" timestamp="29 Aug 2016 17:48:04 GMT" time="2.111" errors="0">
  <testcase name="bluecoatcloud_DirectProvider_tests" time="0.901" classname="com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest">
    <failure type="java.lang.AssertionError" message="No resposne from API. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No resposne from API. expected [true] but found [false]
	at com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest.bluecoatcloud_DirectProvider_tests(BlueCoatThreatPulseTest.java:280)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bluecoatcloud_DirectProvider_tests -->
  <testcase name="bluecoatcloud_DirectProvider_tests" time="0.328" classname="com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest">
    <failure type="java.lang.AssertionError" message="No resposne from API. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No resposne from API. expected [true] but found [false]
	at com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest.bluecoatcloud_DirectProvider_tests(BlueCoatThreatPulseTest.java:280)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bluecoatcloud_DirectProvider_tests -->
  <testcase name="bluecoatcloud_DirectProvider_tests" time="0.337" classname="com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest">
    <failure type="java.lang.AssertionError" message="No resposne from API. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No resposne from API. expected [true] but found [false]
	at com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest.bluecoatcloud_DirectProvider_tests(BlueCoatThreatPulseTest.java:280)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bluecoatcloud_DirectProvider_tests -->
  <testcase name="bluecoatcloud_DirectProvider_tests" time="0.313" classname="com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest">
    <failure type="java.lang.AssertionError" message="No resposne from API. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No resposne from API. expected [true] but found [false]
	at com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest.bluecoatcloud_DirectProvider_tests(BlueCoatThreatPulseTest.java:280)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bluecoatcloud_DirectProvider_tests -->
</testsuite> <!-- Blue coat cloud Service Tests  -->
